name: format
on: 
  push:

jobs:
  format:
    uses: Geode-solutions/actions/.github/workflows/format.yml@master
    secrets:
      TOKEN: ${{ secrets.TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: [format]
